// Renders WebP variants generated by scripts/generate-image-variants.mjs
// (see that file for why this is a build-time script rather than a runtime
// CDN). Falls back to a plain <img> — no <picture>/srcset — for anything
// that isn't a known static /images/product-*.{jpg,png} path, since that's
// the only set this pipeline actually generates variants for; guessing at a
// variant that doesn't exist would just add a failed request.
const WIDTHS = [480, 800, 1200] as const;
const DEFAULT_SIZES = '(max-width: 640px) 480px, (max-width: 1024px) 800px, 1200px';

function toWebpSrcSet(src: string): string | null {
  const match = src.match(/^\/images\/(product-[^/]+)\.(jpe?g|png)$/i);
  if (!match) return null;
  const stem = match[1];
  return WIDTHS.map((w) => `/images/${stem}-${w}w.webp ${w}w`).join(', ');
}

interface Props {
  src: string;
  alt: string;
  className?: string;
  loading?: 'lazy' | 'eager';
  fetchPriority?: 'high' | 'low' | 'auto';
  sizes?: string;
}

export function ResponsiveImage({ src, alt, className, loading = 'lazy', fetchPriority, sizes = DEFAULT_SIZES }: Props) {
  const srcSet = toWebpSrcSet(src);

  if (!srcSet) {
    return <img src={src} alt={alt} className={className} loading={loading} fetchPriority={fetchPriority} />;
  }

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img src={src} alt={alt} className={className} loading={loading} fetchPriority={fetchPriority} />
    </picture>
  );
}
